package: prozer
version: '2.0 beta10'
author: Yakamara Media GmbH & Co. KG
supportpage: www.prozer.org
package: prozer

requires:
  packages:
    xform: '>=3.0.3'
    xform/manager: '>=3.0.3'
    phpmailer: '>=1'