version: '2.0 beta2'
author: Yakamara Media GmbH & Co. KG
supportpage: www.prozer.org
package: prozer

requires:
  addons:
    xform:
      min-version: '3.0.2'
      plugins:
        manager:
          min-version: '3.0'
